config/routes.rb
Networkmill::Application.routes.draw do

  #============================
  # Mobile Routes
  #============================
 
  # Enable mobile subdomain
  # To access it use http://m.lvh.me:3000 or http://m.networkmill.dev
  match '', :to => 'mobile#index', :constraints => lambda { |r| r.subdomain.present? && r.subdomain != 'www' }

  get "/networking" => "mobile#add_contact", :as => 'add_mobile_contact'
  post "/mobile-create-contact" => "mobile#create_contact", :as => 'mobile_create_contact'
  post "/update-mobile-user" => "mobile#update_mobile_user", :as => 'update_mobile_user'
  get "/forgot-password" => "mobile#forgot_password", :as =>'forgot_password'

  get "/m-feedback" => "mobile#feedback", :as => 'mobile_feedback'
  post "/m-feedback" => "mobile#post_feedback", :as => 'post_mobile_feedback'


  #============================
  # Desktop Routes
  #============================

  root :to => "home#index"

  resources :contacts
  resources :users, :only => [:new, :update]

  # first_time aka: onboarding/ tutorial
  get "welcome" => "home#welcome", :as => 'welcome'
  post "first-time-off" => "home#first_time_off", :as => 'first_time_off'
  post "first-time-on" => "home#first_time_on", :as => 'first_time_on'

  get "/dashboard" => "home#dashboard", :as => 'dashboard'
  post "/new-category" => "home#create_category", :as => 'new_category'
  
  # the trick
  get "/preferences" => "users#edit", :as => 'preferences'
  put "/preferences" => "users#update", :as => 'update_preferences'
  # end
  
  get "/check_email/:email" => "users#check_email", :as => 'check_email', :constraints => { :email => /[^\/]+/ }
  
  get "/export-contacts" => "users#export_contacts", :as => 'export_contacts'
  post "/import-contacts" => "users#import_contacts", :as => 'import_contacts'

  post "/send_test_email" => "users#send_test_email", :as => 'send_test_email'
  get "/privacy-policy" => "home#privacy_policy", :as => 'privacy_policy'
  get "/tos" => "home#tos", :as => 'tos'
  get "/faq" => "home#faq", :as => 'faq'

  get "/feedback" => "home#feedback", :as => 'feedback'
  post "/feedback" => "home#post_feedback", :as => 'post_feedback'

  # Allow user to text himself the app url
  post "/send-text" => "home#send_text", :as => 'send_text'

  #============================
  # Devise overrides
  #============================
  # Overriding devise after_sign_up_path to take you to the registration controller
  devise_for :users, :controllers => { :registrations => "registrations" }

  # Overriding devise root_url
  devise_scope :users do
    get 'users', :to => 'home#dashboard', :as => :user_root
  end

  #============================
  # Add beta codes
  #============================

  get "/invite" => "home#beta_invite_dashboard", :as => "beta_invites"
  post "/invite" => "home#create_beta_invite", :as => "create_beta_invite"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :event_queue
  has_many :contacts
  has_many :emails
  has_many :social_networks
  has_many :feedback
  has_many :categories

  attr_accessible :name, :email, :unsubscribed, :desktop_client, :network_mode, :contact_intensity, :avatar, :password, :remember_me, :signature, :feedback, :social_networks_attributes, :first_time, :tel_number

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  accepts_nested_attributes_for :social_networks, :allow_destroy => true

  mount_uploader :avatar, AvatarUploader

  # =================================
  # Validations
  # =================================

  # Validate that user has been added to the beta list
  before_validation :beta_invited?, :on => :create
  def beta_invited?
    unless BetaInvite.exists?(:email=>email)
      errors.add :email, "is not on our beta list"  
    end
  end

  validates :contact_intensity, :numericality => { :only_integer => true, :less_than_or_equal_to => :contact_validation}, :on => :update
  # Ensure that contact intensity is less than the # of contacts the user has. Default intensity = 3
  def contact_validation
    if contacts.count > $initial_contact_intensity
      contacts.count
    else
      $initial_contact_intensity
    end
  end

  # =================================
  # Default values & after create
  # =================================

  $initial_contact_intensity = 3

  # User defaul values once created with Devise
  before_create :user_default_values
  def user_default_values
    self.contact_intensity = $initial_contact_intensity
    self.desktop_client = 'false'
  end

  after_create :create_default_contact_category
  def create_default_contact_category
    self.categories.create(:name => "Uncategorized")
  end

  # Send user welcome email upon sign up
  after_create :send_welcome_mail if Rails.env != "test"
  def send_welcome_mail
    UserMailer.delay.send_welcome_email(self)
  end

  # =================================
  # Select random contacts
  # =================================

  # Picks n random contacts from those in rotation
  # - resets the list as soon as it's finished a rotation
  # - won't return the same contact more than once per list
  # - returns false if you ask for more contacts than the user has (to prevent doubling)
  def pick_random_contacts(n = contact_intensity)
    result = []
    return nil if n > contacts.count
    move_just_sent_to_out
    while result.count < n
      reset_list if contacts_in_rotation.count == 0
      contact = contacts_in_rotation.shuffle.first
      unless result.include?(contact)
      	result << contact.id
      	contact.update_attributes :state => "just_sent"
      end
    end
    return result
  end

  # Get the contacts that are currently in rotation
  def contacts_in_rotation
    contacts.select{ |c| c.state == "in" }
  end

  # Get the contacts that were suggested in the last email
  def contacts_just_sent
    contacts.select{ |c| c.state == "just_sent" }
  end

  # Get the contacts that are currently out of rotation
  def contacts_out
    contacts.select{ |c| c.state == "out" }
  end

  # Move the "just sent" contacts to "out"
  def move_just_sent_to_out
    contacts_just_sent.each do |c|
      c.update_attributes :state => "out"
    end
  end

  # Set contacts that were "out" to "in"
  def reset_list
    contacts.each do |c| 
      c.update_attributes :state => "in"
    end
  end

  # =================================
  # Mobile networking mode
  # =================================

  # This is triggered from the User Controller or the Rake task. This will destroy the
  # event queue and send a summary email of contacts the user just met
  def destroy_queue_and_send_email
    all_contacts = contacts.find_all_by_event_queue_id(event_queue.id)
    @contacts = []
    
    all_contacts.each do |c|
      @contacts << c.id
    end

    UserMailer.delay.send_network_mode_contact_summary(self, @contacts)
    update_attributes(:network_mode => false)
    EventQueue.find_by_user_id(self).destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!, :except => [:check_email, :update]

  # Allow user to export contacts in csv
  require 'csv'
  def export_contacts
      file = CSV.generate do |csv|
        csv << ["Name", "Email", "Category", "Note"]
        current_user.contacts.each do |c|
          csv << [c.name, c.email, Category.find_by_id(c.category_id).name, c.note]
        end
      end
      send_data file, :type => 'text/csv; charset=iso-8859-1; header=present', :disposition => "attachment;filename=my_networkmill_contacts.csv" 
  end

  #Allow user to import contacts in csv
  def import_contacts
    # Get the csv file from the params
    file = params[:csv_file]

    if file.present? && file.content_type == "text/csv"
      # Loop through each row of the csv file
      CSV.foreach(file.tempfile, :headers => true) do |row|
        # Find or create the cotact category for the current_user  
        category = current_user.categories.find_or_create_by_name(row[2])
        
        # Create contacts for the current user, csv columns are found with row[position]
        @new_contact = Contact.create(user_id: current_user.id, name: row[0], email: row[1], category_id: category.id,note: row[3])
      end

      # Check that the last row was saved, note: this needs to be revised to avoid edge cases
      if @new_contact.save
        redirect_to preferences_path, notice: "contacts saved"
      else
        redirect_to preferences_path, notice: "ohh no, there was an error - are you sure these are new contacts?"
      end
    else
      redirect_to preferences_path, :notice => "hmm, you need a csv file for this to work"
    end 
  end


  def index
    @users = User.find_all_by_id(current_user)
  end

  def show
    @user = current_user
  end

  def new
    @user = User.new
  end

  def edit
    @user = current_user
  end

  def update
    # TODO: before deploying, we should test this to make sure authentication is working

    # if user is resetting password, reset the password and redirect to root
    if params[:user][:reset_password_token]
      User.reset_password_by_token(params[:user])
      redirect_to root_url, notice: 'password reset successfully!'
    # if user is updating their preferences, make sure to authenticate
    else
      authenticate_user!
      @user = current_user
      password_fields = [params[:user][:current_password], params[:user][:password]]
      # if they are updating anything except the password, no need to pass authenticate
      if password_fields.reject {|p| p.empty? }.empty?
        @user.update_without_password(params[:user])
        send_test_email if params[:send_test_email]
      # if they are trying to update their password, make sure it's right
      else
        @user.update_with_password(params[:user])
      end

      # If user is using test email show one notice, if not show another
      if params[:send_test_email]
        redirect_to preferences_path, :notice => "check your email for a special surprise ;)"
      else
        redirect_to dashboard_path, :notice => "sweet, your preferences have been updated!"
      end
    end

  end

  # Allow user to send itself a test email from the preference panel
  def send_test_email
    # Send mail without delayed job:
    # UserMailer.new_contact_intro_email(current_user, current_user).deliver
    # Send mail with delayed job (to get delayed_job working in development run $rake jobs:work)

    UserMailer.delay.new_contact_intro_email(current_user, current_user)
  end

  def destroy
    current_user.destroy
    redirect_to root_url
  end

  def check_email
    if User.find_by_email(params[:email])
      render :text => "registered"
    elsif BetaInvite.find_by_email(params[:email]).nil?
      render :text => "not_beta"
    else
      render :text => "false"
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
#settings
  
  %h2 Settings

  = form_for @user, url: update_preferences_path do |f|
    - if @user.errors.any?
      #error_explanation
        %h2
          =pluralize(@user.errors.count, "error")
          prohibited this user from being saved:

        %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

    %h3 Edit Introductory Email

    #email-window
      .top-bar
        %ul
          %li.close
          %li.min
          %li.max

      .address-fields
        .from
          %label From:
          .avatar
          = f.text_field :name, placeholder: "name?"
          .email
            (
            = f.text_field :email
            )
        .to
          %label To:
          .avatar
          %p all the awesome people you'll meet

      .email-body
        = f.text_area :signature, :rows => "8", placeholder: "Write your intro email here!"

        / .contact-card
        /   = f.file_field :avatar
        /   = image_tag @user.avatar_url(:full), class: 'avatar'
        /   .name Jeff Escalante
        /   .email hello@jenius.me

        /   #social-networks{ :'data-count' => "#{@user.social_networks.count}" }
        /     = f.fields_for :social_networks do |q|
        /       .social-field
        /         = q.hidden_field :name
        /         = q.text_field :link
        /         = q.hidden_field :_destroy

        /     / %a.add-field add field

        /   %ul.social
        /     %li.twitter
        /       %a
        /     %li.linkedin
        /       %a
        /     %li.facebook
        /       %a
        /     %li.gplus
        /       %a

      .actions
        = f.submit "send me a test copy", :class => "test-button", :name => "send_test_email"
        = f.submit "update", :class => "update"

    #other-prefs
      %h3 Other Preferences

      / .desktop-client
      /   = f.label :desktop_client, "I use a desktop email client: "
      /   = f.check_box :desktop_client

      .contact-intensity
        = f.label :contact_intensity, "Remind me to stay in touch with this many contacts each week:"
        = f.text_field :contact_intensity, :size => 1

      %h4 Change my password:
      .current
        = f.label :current_password, "current password"
        = f.password_field :current_password
      .new
        = f.label :password, "new password"
        = f.password_field :password, :autocomplete => "off" 

      = f.submit "save"
      
      = link_to "Export my contacts (.csv)", export_contacts_path, class: 'export-contacts'
      = link_to "Show me the welcome tutorial", first_time_on_path, :method => :post, class: 'export-contacts'

    / #bad-things
    /   .field
    /     = f.label :unsubscribed, "Do not receive any email from us"
    /     = f.select :unsubscribed, {"yes" => true, "no" => false}
    /   .field
    /     = link_to "Cancel my account", registration_path(resource_name), :confirm => "Are you sure?", :method => :delete
 
  / NOTE && TODO: Clean the br/ below

#upload-contacts
  %h2
    Upload Contacts from CSV (name, email, category, note)
  = form_tag("/import-contacts", :method => :post, :multipart => true) do
    %label{:for => "csv_file"} CSV to Upload
    = file_field_tag "csv_file"
    = submit_tag "import file", class: "import"
  

app/views/users/edit.html.haml
- if @user.name.blank?
  %h2 Let's get to know each other, why don't you tell us your name?
= render 'form'

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Desktop client</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.desktop_client %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Desktop client:</b>
  <%= @user.desktop_client %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>