config/routes.rb
Networkmill::Application.routes.draw do

  #============================
  # Mobile Routes
  #============================
 
  # Enable mobile subdomain
  # To access it use http://m.lvh.me:3000 or http://m.networkmill.dev
  match '', :to => 'mobile#index', :constraints => lambda { |r| r.subdomain.present? && r.subdomain != 'www' }

  get "/networking" => "mobile#add_contact", :as => 'add_mobile_contact'
  post "/mobile-create-contact" => "mobile#create_contact", :as => 'mobile_create_contact'
  post "/update-mobile-user" => "mobile#update_mobile_user", :as => 'update_mobile_user'
  get "/forgot-password" => "mobile#forgot_password", :as =>'forgot_password'

  get "/m-feedback" => "mobile#feedback", :as => 'mobile_feedback'
  post "/m-feedback" => "mobile#post_feedback", :as => 'post_mobile_feedback'


  #============================
  # Desktop Routes
  #============================

  root :to => "home#index"

  resources :contacts
  resources :users, :only => [:new, :update]

  # first_time aka: onboarding/ tutorial
  get "welcome" => "home#welcome", :as => 'welcome'
  post "first-time-off" => "home#first_time_off", :as => 'first_time_off'
  post "first-time-on" => "home#first_time_on", :as => 'first_time_on'

  get "/dashboard" => "home#dashboard", :as => 'dashboard'
  post "/new-category" => "home#create_category", :as => 'new_category'
  
  # the trick
  get "/preferences" => "users#edit", :as => 'preferences'
  put "/preferences" => "users#update", :as => 'update_preferences'
  # end
  
  get "/check_email/:email" => "users#check_email", :as => 'check_email', :constraints => { :email => /[^\/]+/ }
  
  get "/export-contacts" => "users#export_contacts", :as => 'export_contacts'
  post "/import-contacts" => "users#import_contacts", :as => 'import_contacts'

  post "/send_test_email" => "users#send_test_email", :as => 'send_test_email'
  get "/privacy-policy" => "home#privacy_policy", :as => 'privacy_policy'
  get "/tos" => "home#tos", :as => 'tos'
  get "/faq" => "home#faq", :as => 'faq'

  get "/feedback" => "home#feedback", :as => 'feedback'
  post "/feedback" => "home#post_feedback", :as => 'post_feedback'

  # Allow user to text himself the app url
  post "/send-text" => "home#send_text", :as => 'send_text'

  #============================
  # Devise overrides
  #============================
  # Overriding devise after_sign_up_path to take you to the registration controller
  devise_for :users, :controllers => { :registrations => "registrations" }

  # Overriding devise root_url
  devise_scope :users do
    get 'users', :to => 'home#dashboard', :as => :user_root
  end

  #============================
  # Add beta codes
  #============================

  get "/invite" => "home#beta_invite_dashboard", :as => "beta_invites"
  post "/invite" => "home#create_beta_invite", :as => "create_beta_invite"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, :only => [:dashboard, :welcome]
  before_filter :beta_invite_auth_admin, :only => [:beta_invite_dashboard, :create_beta_invite]
  
  def index
    redirect_to dashboard_path if current_user
  end  

  def welcome
    redirect_to dashboard_path if !current_user.first_time
  end

  def dashboard
    redirect_to welcome_path if current_user.first_time
    @user = current_user
    
    @contacts = Contact.find_all_by_user_id(current_user.id).reverse
    @contact = Contact.new

    @categories = current_user.categories
    @category = Category.new
  end

  # =================================
  # First time (tutorial mode)
  # =================================

  # Turn first_time off from welcome screen
  def first_time_off
    current_user.update_attributes(:first_time => false)
    redirect_to dashboard_path if !current_user.first_time
  end

  # Turn first_time on from preference menu
  def first_time_on
    current_user.update_attributes(:first_time => true)
    redirect_to welcome_path if current_user.first_time
  end

  # =================================
  # Twilio
  # =================================

  def send_text
    number = params[:number]

    @client = Twilio::REST::Client.new TWILIO_SID, TWILIO_AUTH
    @client.account.sms.messages.create(
      :from => '+16464806552', # This is our Twilio number
      :to => "#{number}",
      :body => "Hey there good looking, go to m.networkmill.com to network like a boss."
    )
    if current_user
      current_user.update_attributes(:tel_number => number)
      redirect_to dashboard_path, :notice => "Schweet, check your phone..."
    else
      redirect_to root_url, :notice => "Schweet, check your phone..."
    end
  end

  # =================================
  # Contact categories
  # =================================

  def create_category
    @category = Category.new(params[:category])
    @category.user = current_user
    if @category.save
      redirect_to dashboard_path, notice: "new contact category created" 
    else
      redirect_to dashboard_path, notice: "ohh no, there was an error creating your category (are you sure it doesn't already exist?)"
    end
  end

  # =================================
  # Feedback
  # =================================

  def feedback
    @feedback = Feedback.new
  end

  def post_feedback
    @feedback = Feedback.new
    @feedback.user_id = current_user.id if current_user.present?
    @feedback.message = params[:feedback][:message]
    @feedback.save!
    UserMailer.delay.send_feedback_to_team(@feedback)
    redirect_to root_url
  end

  # =================================
  # Beta invites
  # =================================

  def beta_invite_dashboard
    @new_beta = BetaInvite.new
    @emails_already_in_beta = BetaInvite.all.reverse
  end

  def create_beta_invite
    @new_beta = BetaInvite.new(params[:beta_invite])
    redirect_to beta_invites_path if @new_beta.save
  end

  protected

  # Basic HTML Authentication for beta invistations
  def beta_invite_auth_admin
    authenticate_or_request_with_http_basic do |username, password|
      username == "ilove" && password == "tits"
    end
  end
  
end

app/helpers/home_helper.rb
module HomeHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/views/home/_categories.html.haml
/ Create new category
= form_for @category, url: new_category_path do |f|
  = f.text_field :name, :id => "add-category-field"
  = f.submit "create contact category", :id => "add-category-button"

/ List all categories
- @categories.each do |category|
  %li
    = category.name

app/views/home/_contact_form.html.haml
- verb ||= "add"

= form_for contact do |f|

  .avatar
    %img.preview{ src: "#{contact.avatar_url(:full) if contact.avatar? }" }
    = f.file_field :avatar, class: 'contact_avatar'
  .fields
    .field
      = f.text_field :email, placeholder: 'email'
    .field
      = f.text_field :name, placeholder: 'name'
    .field
      = f.collection_select(:category_id, current_user.categories.all, :id, :name)
    .add-notes
      %span add notes...
      .field
        = f.text_area :note
  .actions
    = f.submit "#{verb} contact &raquo;".html_safe

app/views/home/_sign_in.html.haml
#sign-in-form
  = form_for(resource, :as => resource_name, :url => session_path(resource_name), :remote => true) do |f|
    = f.email_field :email, placeholder: 'email', class: 'email-field'
    = f.password_field :password, placeholder: 'password', class: 'password-field'

    / - if devise_mapping.rememberable?
    /   = f.check_box :remember_me
    /   = f.label :remember_me

    - if devise_mapping.recoverable? && controller_name != 'passwords'
      = link_to "forgot password?", new_password_path(resource_name), class: 'forgot-pass'

    = f.submit "hit it &raquo;".html_safe, class: 'form-submit'

  = render partial: "home/forgot_password"

app/views/home/_sign_up.html.haml
%h4 sign up!

= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f|
  = devise_error_messages!
  = f.email_field :email, placeholder: 'email', class: 'email-field'
  / Provide a hint for Kicksend email checker
  #hint
    did you mean
    %span
  = f.password_field :password, placeholder: 'password', class: 'password-field'\
  %input.pass-visible{ type: 'text', placeholder: 'password' }
  .show-checkbox
    %input#show-pass{ type: 'checkbox', name: 'show' }
    %label{ for: 'show-pass' } show password

  = f.submit "let's go &raquo;".html_safe, class: 'form-submit'

app/views/home/_text_app_url.html.haml
/ Allow user to send him/herself the networkmill app download URL
#text-app
  = form_tag("/send-text", class: "text_user", method: "post") do
    = text_field_tag "number",nil, placeholder: "what's your number", :class => "telephone-field"
    = submit_tag "send me the app link &raquo;".html_safe, :class => "form-submit"

app/views/home/beta_invite_dashboard.html.haml
%h1
  Create a new invite
  
= form_for @new_beta do |f|
  = f.text_field :email
  = f.submit

%br

%h2 
  Emails already invited

- @emails_already_in_beta.each do |beta|
  %li
    = beta.email 

app/views/home/dashboard.html.haml
- if @contact.errors.any?
  .flash.errors
  - @contact.errors.full_messages.each do |err|
    = err

.top
  %h3 Here are the people you want to stay in touch with:
  = link_to new_contact_path, :class => 'new-contact-button' do
    %span
    add new contact

  .add-contact
    = render partial: 'contact_form', :locals => { :contact => @contact }

.categories
  %p
    = link_to 'manage contact categories', "#", :id => "expand-categories"
  #manage-categories
    = render partial: 'categories', :locals => { :contact => @contact }

%ul.contacts
  - @contacts.each do |contact|
    %li
      = image_tag contact.avatar_url(:thumb)
      %p
        = contact.name
        %span= "(#{contact.email})"
        - unless contact.category.nil?
          %span= " - #{contact.category.name}"
      .right
        = link_to 'Delete', contact, confirm: 'For real?', method: :delete, class: 'delete-contact'
        = link_to 'Edit', edit_contact_path(contact), class: 'edit-contact'
    .editing-contact
      = render partial: 'contact_form', :locals => { :contact => contact , :verb => 'edit' }

-if @contacts.size < 3
  .few-contacts
    %h3
      Hey there good looking, looks like you could use some more contacts... 
    %p
      Why not add some of your ex co-workers? Or what about that entrepreneurial friend of yours - yes, the one building a Facebook for cats. You could also add the people who's business cards you have in your wallet - or even those that have sent you a recommendation on LinkedIn.
    %p
      Heading out to an event? We've got you covered with our fancy little mobile app.
    = render partial: "text_app_url"

app/views/home/faq.html.haml
%h1
  F.A.K. - Frenquently Asked Kuestions

%ol
  %li
    What is NetworkMill?
    %p
      It's a tool to help you stay in touch with the interesting people you meet. How many times have you exchanged business cards and never spoken again? When was the last time you reached to past co-workers - whose company you enjoyed? You can think of NetworkMill as your second (socially oriented) brain.
      %br
      %br

  %li 
    Who is NetworkMill for?
    %p 
      NetworkMill is ideal for the busy, business oriented, ones and for social butterflies. Whether you are working on your own startup, attending an MBA program or simply meeting tons of people, NetworkMill is for you. We all know how powerful a good network of contacts can be.
      %br
      %br

  %li
    How much does NetworkMill cost?
    %p
      NetworkMill will always have a free version. As we add advanced features we may create a premium plan which may cost around $5 - $9 per month. (We don't know the exact price yet since we still have a long road to go before crossing that bridge.) 
    %p
      During our beta offer we also offer a supporter account - for the generous ones. Your contribution allows us to pay for our server costs (and, on some occasions, for a warm cup of coffee). By becoming a NetworkMill supporters you not only show your appreciation but also give us, independent developpers, the honor of knowing that you value our work and efforts.
  %li
    How does NetworkMill work?
    %p
      When you meet someone you add them to NetworkMill either through our mobile app or via this web interface. Every week we send you an email suggesting who you should get in touch with. 
    %p 
      Note: All your contact information belongs to you and you can export your contacts from NetworkMill at any time.

app/views/home/feedback.html.haml
%h1
  Feedback

%p
  We want to hear your feedback to make NetworkMill better.

= form_for(@feedback, :url => post_feedback_path, :method => 'post') do |f|
  .field
    = f.text_area :message, :id => "feedback-box"

  .actions
    = f.submit "Send", :id => "send-feedback"

app/views/home/index.html.haml
#splash
  %img{ src: 'assets/splash.png', alt: 'networkmill' }
  .wrap
    = link_to "sign up, free &raquo;".html_safe, new_user_registration_path, class: 'sign-up'

#home
  %h2 networkmill keeps track of your contacts and makes sure you stay in touch

  %ul.summary
    %li
      = image_tag 'step1.png'
      %p add people you want to stay in touch with
    %li
      = image_tag 'step2.png'
      %p get reminders every few weeks
    %li
      = image_tag 'step3.png'
      %p create new connections with our amazing app
      =render partial: 'text_app_url'


#sign-up
  = render partial: 'sign_up'

app/views/home/privacy-policy.html.haml
%h1
  NetworkMill’s Privacy Policy

%br
%h2
  Privacy Policy - For you and I:

%p
  NetworkMill values and respects its users and visitors. We will 
  %strong
    never share your data 
  or do anything sketchy with it. It is important for you to know that 
  %strong
    your data is your data (yes, you own it – we don’t). 
  You can export your data at any time and if you choose to delete your account, it will be permanently deleted (none of this “would you like to restore your account” – if you were to delete your account, it’s gone forever).

%p
  Social Media integration is 100% optional and 
  %strong
    we will never 
  Tweet, Post, Message, Follow or do anything without your authorization.

%p
  Please note that we use Google Analytics to monitor our site, therefore, your computer will most likely be cookied by Google (no worries, most websites on the web use Google Analytics too). This privacy policy may change in the future but our core values will always stay the same. 

%p
  If you have any questions or concerns please email Carl at carl[at]networkmill.com or hi[at]networkmill.com.

%br
%h2
  Privacy Policy - For lawyers and nerds:

%p
  At NetworkMill, we collect and manage user data according to the following Privacy Policy, with the goal of incorporating our company values: transparency, accessibility, sanity, usability. This document is part of NetworkMill's Terms of Service, and by using NetworkMill.com (the “Website”), you agree to the terms of this Privacy Policy and the Terms of Service. Please read the Terms of Service in their entirety, and refer to those for definitions and contacts.

%br
%h3
  Data Collected

%p
  We collect anonymous data from visitors of the Website to monitor traffic and fix bugs. For example, we may collect information like web requests, the data sent in response to such requests, the Internet Protocol address, the browser type, the browser language, and a timestamp for the request.

%p
  We ask you to log in and provide certain personal information (such as your name and email address) in order to be able to save your profile and contacts and comments associated with it.  In order to enable these or any other login-based features, we use cookies to store session information for your convenience. You can block or delete cookies and still be able to use NetworkMill, although if you do you will then be asked for your username and password every time you log in to the Website. In order to take advantage of certain features of the Website, you may also choose to provide us with other personal information, such as your picture or brief intro, but your decision to utilize these features and provide such data will always be voluntary.

%p
  You are able to view, change and remove your data associated with your profile. Should you choose to delete your account, please contact us at hi@NetworkMill.com and we will follow up with such request as soon as possible. You can also modify your notification preferences by clicking the appropriate link included in the footer of email notifications.

%br
%h3
  Use of the Data

%p
  We only use your personal information to provide you the NetworkMill services or to communicate with you about the services or the Website.

%p
  With respect to any contacts you may choose to add to NetworkMill, we take the privacy and confidentiality of such contacts seriously. We employ industry standard techniques to protect against unauthorized access of data about you that we store, including personal information. 

%p
  We do not share personal information you have provided to us without your consent, unless:

%ul
  %li
    doing so is appropriate to carry out one of your requests;
  %li
    we believe it's needed to enforce our Terms of Service, or that is legally required;
  %li
    we believe it's needed to detect, prevent or address fraud, security or technical issues;
  %li
    otherwise protect our property, legal rights, or that of others.

%p
  NetworkMill is operated from the United States.  If you are visiting the Website from outside the U.S., you agree to any processing of any personal information you provide us according to this policy.

%p
  NetworkMill may contact you, by email or other means. For example, NetworkMill may send you promotional emails relating to NetworkMill or communicate with you about your use of the NetworkMill website. NetworkMill may also use technology to alert us via a confirmation email when you open an email from us. If you do not want to receive email from NetworkMill, please opt out of receiving emails at the bottom of any NetworkMill emails.

%br
%h3
  Sharing of Data

%p
  We do NOT share your personal information with third parties. We currently use Google Analytics (traffic analysis, SEO optimization), Stripe (to process payments) and Mandrill (mailing list management). We listed below what data these third parties extract exactly. Feel free to check out their own Privacy Policies to find out more. 

%ul
  %li
    Google Analytics: anonymous (ad serving domains, browser type, demographics, language settings, page views, time/date), pseudonymous (IP address)
  %li
    Stripe: securely process your credit card payments; all information is kept strictly confidential.
  %li
    Mandrill: name and email of our beta subscription list.

%p
  We also use social buttons provided by services like Twitter, Google+, LinkedIn and Facebook. Your use of these third party services is entirely optional. We are not responsible for the privacy policies and/or practices of these third party services, and you are responsible for reading and understanding those third party services’ privacy policies.

%p
  We may choose to buy or sell assets. In these types of transactions, user information is typically one of the transferred business assets. Moreover, if we, or substantially all of our assets, were acquired, or if we go out of business or enter bankruptcy, user information would be one of the assets that is transferred or acquired by a third party. You acknowledge that such transfers may occur, and that any acquirer of us or our assets may continue to use your personal information as set forth in this policy.

%br
%h3
  Changes to the Privacy Policy

%p
  We may amend this Privacy Policy from time to time. Use of information we collect now is subject to the Privacy Policy in effect at the time such information is used. If we make changes in the way we collect or use information, we will notify you by posting an announcement on the Website or sending you an email. A user is bound by any changes to the Privacy Policy when he or she uses the Services after such changes have been first posted.

%p
  Should you have any question or concern, please do not hesitate to contact us at hi@NetworkMill.com.
%br
%br

app/views/home/privacy_policy.html.haml
%h1
  NetworkMill’s Privacy Policy

%br
%h2
  Privacy Policy - For you and I:

%p
  NetworkMill values and respects its users and visitors. We will 
  %strong
    never share your data 
  or do anything sketchy with it. It is important for you to know that 
  %strong
    your data is your data (yes, you own it – we don’t). 
  You can export your data at any time and if you choose to delete your account, it will be permanently deleted (none of this “would you like to restore your account” – if you were to delete your account, it’s gone forever).

%p
  Social Media integration is 100% optional and 
  %strong
    we will never 
  Tweet, Post, Message, Follow or do anything without your authorization.

%p
  Please note that we use Google Analytics to monitor our site, therefore, your computer will most likely be cookied by Google (no worries, most websites on the web use Google Analytics too). This privacy policy may change in the future but our core values will always stay the same. 

%p
  If you have any questions or concerns please email Carl at carl[at]networkmill.com or hi[at]networkmill.com.

%br
%h2
  Privacy Policy - For lawyers and nerds:

%p
  At NetworkMill, we collect and manage user data according to the following Privacy Policy, with the goal of incorporating our company values: transparency, accessibility, sanity, usability. This document is part of NetworkMill's Terms of Service, and by using NetworkMill.com (the “Website”), you agree to the terms of this Privacy Policy and the Terms of Service. Please read the Terms of Service in their entirety, and refer to those for definitions and contacts.

%br
%h3
  Data Collected

%p
  We collect anonymous data from visitors of the Website to monitor traffic and fix bugs. For example, we may collect information like web requests, the data sent in response to such requests, the Internet Protocol address, the browser type, the browser language, and a timestamp for the request.

%p
  We ask you to log in and provide certain personal information (such as your name and email address) in order to be able to save your profile and contacts and comments associated with it.  In order to enable these or any other login-based features, we use cookies to store session information for your convenience. You can block or delete cookies and still be able to use NetworkMill, although if you do you will then be asked for your username and password every time you log in to the Website. In order to take advantage of certain features of the Website, you may also choose to provide us with other personal information, such as your picture or brief intro, but your decision to utilize these features and provide such data will always be voluntary.

%p
  You are able to view, change and remove your data associated with your profile. Should you choose to delete your account, please contact us at hi@NetworkMill.com and we will follow up with such request as soon as possible. You can also modify your notification preferences by clicking the appropriate link included in the footer of email notifications.

%br
%h3
  Use of the Data

%p
  We only use your personal information to provide you the NetworkMill services or to communicate with you about the services or the Website.

%p
  With respect to any contacts you may choose to add to NetworkMill, we take the privacy and confidentiality of such contacts seriously. We employ industry standard techniques to protect against unauthorized access of data about you that we store, including personal information. 

%p
  We do not share personal information you have provided to us without your consent, unless:

%ul
  %li
    doing so is appropriate to carry out one of your requests;
  %li
    we believe it's needed to enforce our Terms of Service, or that is legally required;
  %li
    we believe it's needed to detect, prevent or address fraud, security or technical issues;
  %li
    otherwise protect our property, legal rights, or that of others.

%p
  NetworkMill is operated from the United States.  If you are visiting the Website from outside the U.S., you agree to any processing of any personal information you provide us according to this policy.

%p
  NetworkMill may contact you, by email or other means. For example, NetworkMill may send you promotional emails relating to NetworkMill or communicate with you about your use of the NetworkMill website. NetworkMill may also use technology to alert us via a confirmation email when you open an email from us. If you do not want to receive email from NetworkMill, please opt out of receiving emails at the bottom of any NetworkMill emails.

%br
%h3
  Sharing of Data

%p
  We do NOT share your personal information with third parties. We currently use Google Analytics (traffic analysis, SEO optimization), Stripe (to process payments) and Mandrill (mailing list management). We listed below what data these third parties extract exactly. Feel free to check out their own Privacy Policies to find out more. 

%ul
  %li
    Google Analytics: anonymous (ad serving domains, browser type, demographics, language settings, page views, time/date), pseudonymous (IP address)
  %li
    Stripe: securely process your credit card payments; all information is kept strictly confidential.
  %li
    Mandrill: name and email of our beta subscription list.

%p
  We also use social buttons provided by services like Twitter, Google+, LinkedIn and Facebook. Your use of these third party services is entirely optional. We are not responsible for the privacy policies and/or practices of these third party services, and you are responsible for reading and understanding those third party services’ privacy policies.

%p
  We may choose to buy or sell assets. In these types of transactions, user information is typically one of the transferred business assets. Moreover, if we, or substantially all of our assets, were acquired, or if we go out of business or enter bankruptcy, user information would be one of the assets that is transferred or acquired by a third party. You acknowledge that such transfers may occur, and that any acquirer of us or our assets may continue to use your personal information as set forth in this policy.

%br
%h3
  Changes to the Privacy Policy

%p
  We may amend this Privacy Policy from time to time. Use of information we collect now is subject to the Privacy Policy in effect at the time such information is used. If we make changes in the way we collect or use information, we will notify you by posting an announcement on the Website or sending you an email. A user is bound by any changes to the Privacy Policy when he or she uses the Services after such changes have been first posted.

%p
  Should you have any question or concern, please do not hesitate to contact us at hi@NetworkMill.com.
%br
%br

app/views/home/welcome.html.haml
%h1
  Hi there, it's nice to see around here!

%p
  This is were some awesome text and some awesome onboarding process will go. It's gonna be so great it'll blow your brains out!

= link_to "ok, got it", first_time_off_path, :method => :post, id: 'turn-turorial-off'