config/routes.rb
Networkmill::Application.routes.draw do

  #============================
  # Mobile Routes
  #============================
 
  # Enable mobile subdomain
  # To access it use http://m.lvh.me:3000 or http://m.networkmill.dev
  match '', :to => 'mobile#index', :constraints => lambda { |r| r.subdomain.present? && r.subdomain != 'www' }

  get "/networking" => "mobile#add_contact", :as => 'add_mobile_contact'
  post "/mobile-create-contact" => "mobile#create_contact", :as => 'mobile_create_contact'
  post "/update-mobile-user" => "mobile#update_mobile_user", :as => 'update_mobile_user'
  get "/forgot-password" => "mobile#forgot_password", :as =>'forgot_password'

  get "/m-feedback" => "mobile#feedback", :as => 'mobile_feedback'
  post "/m-feedback" => "mobile#post_feedback", :as => 'post_mobile_feedback'


  #============================
  # Desktop Routes
  #============================

  root :to => "home#index"

  resources :contacts
  resources :users, :only => [:new, :update]

  # first_time aka: onboarding/ tutorial
  get "welcome" => "home#welcome", :as => 'welcome'
  post "first-time-off" => "home#first_time_off", :as => 'first_time_off'
  post "first-time-on" => "home#first_time_on", :as => 'first_time_on'

  get "/dashboard" => "home#dashboard", :as => 'dashboard'
  post "/new-category" => "home#create_category", :as => 'new_category'
  
  # the trick
  get "/preferences" => "users#edit", :as => 'preferences'
  put "/preferences" => "users#update", :as => 'update_preferences'
  # end
  
  get "/check_email/:email" => "users#check_email", :as => 'check_email', :constraints => { :email => /[^\/]+/ }
  
  get "/export-contacts" => "users#export_contacts", :as => 'export_contacts'
  post "/import-contacts" => "users#import_contacts", :as => 'import_contacts'

  post "/send_test_email" => "users#send_test_email", :as => 'send_test_email'
  get "/privacy-policy" => "home#privacy_policy", :as => 'privacy_policy'
  get "/tos" => "home#tos", :as => 'tos'
  get "/faq" => "home#faq", :as => 'faq'

  get "/feedback" => "home#feedback", :as => 'feedback'
  post "/feedback" => "home#post_feedback", :as => 'post_feedback'

  # Allow user to text himself the app url
  post "/send-text" => "home#send_text", :as => 'send_text'

  #============================
  # Devise overrides
  #============================
  # Overriding devise after_sign_up_path to take you to the registration controller
  devise_for :users, :controllers => { :registrations => "registrations" }

  # Overriding devise root_url
  devise_scope :users do
    get 'users', :to => 'home#dashboard', :as => :user_root
  end

  #============================
  # Add beta codes
  #============================

  get "/invite" => "home#beta_invite_dashboard", :as => "beta_invites"
  post "/invite" => "home#create_beta_invite", :as => "create_beta_invite"

end

app/controllers/mobile_controller.rb
class MobileController < ApplicationController
layout "mobile"
before_filter :authenticate_user!, :except => ['index', 'forgot_password']

  def index
    redirect_to add_mobile_contact_path if current_user
  end

  def update_mobile_user
    @user = current_user
    redirect_to add_mobile_contact_path if @user.update_without_password(params)

    # If network_mode == on create EventQueue, else destroy EventQueue and send summary email to user
    if @user.network_mode?
      # Create an EventQueue only if the user has none
      EventQueue.create(:user_id => @user.id) unless @user.event_queue.present?
    else
      # Ensure that user has an open EventQueue and destroy it
      @user.destroy_queue_and_send_email if @user.event_queue.present?
    end
  end

  def add_contact
    @contact = Contact.new
    @user = current_user
  end

  def create_contact
    @contact = Contact.new(params)
    @contact.user = current_user
    @contact.state = "in"

    @success = true if @contact.save
    
    # Add contact to user_event_queue if networkmode is on
    @contact.update_attributes(event_queue_id: "#{@contact.user.event_queue.id}") if @contact.user.network_mode?
    
    # Send contact intro email
    UserMailer.delay.new_contact_intro_email(current_user, @contact)  
  end

  def feedback
    @feedback = Feedback.new
  end

  def post_feedback
    @feedback = Feedback.new
    @feedback.user_id = current_user.id if current_user.present?
    @feedback.message = params[:feedback][:message]
    @feedback.save!
    UserMailer.delay.send_feedback_to_team(@feedback)
    redirect_to add_mobile_contact_path
  end

end

app/views/mobile/add_contact.html.haml
/ Add new contact
#errors
#card

  #add-contact
    %h1 NetworkMill
    
    #counter
      - if current_user.network_mode
        = current_user.event_queue.contacts.count

    = form_tag(mobile_create_contact_path, :method => "post", :remote => true) do
      = text_field_tag :name, nil, :placeholder => 'name', :value => @contact.name
      = text_field_tag :email, nil, :placeholder => 'your@email.com', :value => @contact.email, :type => 'email'
      = text_area_tag :note, nil, :id => 'write-note', :placeholder => "how did you meet? (optional)"
      .actions
        = submit_tag "send &raquo;".html_safe

    .cog
      %span

  / Mobile preference menu

  #preference
    %header
      %h1 networkmill
    #bio
      #picture
      #name
        = @user.name.titleize if @user.name.present?
      #email
        = @user.email
      = link_to "account settings &raquo;".html_safe, root_url(:subdomain => false), :class =>"account-settings"
      = link_to "feedback &raquo;".html_safe, mobile_feedback_path, :class => "account-settings", :id => "feedback-tab"

    #signature
      = form_tag(update_mobile_user_path, :method => "post") do
        = text_area_tag :signature, @user.signature
        
        #networking-mode
          %p
            Event Mode
            = select_tag :network_mode, options_for_select([["On", true], ["Off", false]], @user.network_mode)

        = submit_tag "start networking &raquo;".html_safe, :id => "start-networking"

app/views/mobile/create_contact.js.erb
$('.mobile-flash > *').remove()

if ("<%= @success %>" == "true") {

  $('.mobile-flash').append("<div class='flash success'>Contact saved!</div>");
  $('.mobile-flash > *').delay(2000).fadeOut();
  setTimeout(function(){ window.location.reload() }, 500);

} else {

  var errors = [];
  <% @contact.errors.full_messages.each do |err| %>
    errors.push("<%= err %>")
  <% end %>
  $('.mobile-flash').append("<div class='flash error'></div>")
  $('.mobile-flash > *').delay(2000).fadeOut();
  for (var i = 0; i < errors.length; i++) {
    $('.error').append("<div>" + errors[i] + "</div>");
  }
  
}

app/views/mobile/feedback.html.haml
#feedback
  #gradient
  %h1
    NetworkMill

  %p
    We want to hear your feedback to make NetworkMill better.

  = form_for(@feedback, :url => post_mobile_feedback_path, :method => 'post') do |f|
    .field
      = f.text_area :message

    .actions
      = f.submit "send feedback &raquo;".html_safe

app/views/mobile/forgot_password.html.haml
#forgot-password
  #gradient
  %h1
    NetworkMill
    
  #reset-password
    = form_for(resource, :as => resource_name, :url => password_path(resource_name), :html => { :method => :post, :id => "forgot-password-form" }, :remote => true) do |f|
      = devise_error_messages!
      = f.email_field :email, placeholder: "my@email.com", class: 'email-field'
      = f.submit "Reset password &raquo;".html_safe, :class => "signin-submit reset-password"
    
  #more-actions
    = link_to "cancel", root_url

app/views/mobile/index.html.haml
#sign-in
  #gradient
  %h1
    NetworkMill

  = form_for(resource, :as => resource_name, :url => session_path(resource_name), :remote => true) do |f|
    = f.email_field :email, placeholder: 'your@email.com', class: 'email'
    = f.password_field :password, placeholder: 'password', class: 'password'

    / - if devise_mapping.rememberable?
    /   = f.check_box :remember_me
    /   = f.label :remember_me

    = f.submit "sign in &raquo;".html_safe, class: 'sign-in-submit'


  #more-actions
    = link_to "sign up", root_url(:subdomain => false)

    - if devise_mapping.recoverable? && controller_name != 'passwords'
      = link_to "forgot password?", forgot_password_path

    